export default [
  { format: '春和', value: 'spring'},
  { format: '冬雪', value: 'winter'},
  { format: '夏日', value: 'summer'},
  { format: ['发光', '燃烧'], value: 'fire' },
  {format: '可爱', value: 'cute' },
  {format: '龙吟新春', value: 'dragon'},
  { format: '猫', value: 'cat'},
  {format: '魔法', value: 'magic'},
  {format: /方形/, value: 'square'},
  {format: /圆角/, value: 'round'},
  {format: /菱形/, value: 'diamond'},
  {format: '泡泡', value: 'qixibubble'},
  {format: '蔷薇', value: 'rose'},
  {format: '赛博', value: 'neon'},
  {format: '赛博猫', value: 'neoncat'},
  {format: '兔年', value: 'rabbit'},
  {format: '星座', value: 'constellation'},
  {format: '原神', value: 'genshin'},
  {format: '科技', value: 'technology'},
]